### ISSUE TITLE
代码渲染能否优化渲染以及相应的格式排版例如优化为第2章图这种

### ISSUE THREAD

**Issue by jiang4yu** [lsylovelmy/hexo-theme-macleaya#1]
![image](https://user-images.githubusercontent.com/50733847/86196514-ff825f00-bb85-11ea-8247-0f1fff010bc6.png)
![image](https://user-images.githubusercontent.com/50733847/86196615-322c5780-bb86-11ea-89f8-c74f963b9cb1.png)

**Comment by ghost** [comment]
同问，这个在作者的blog中是怎么实现的 @lsylovelmy

**Comment by lsy-loren** [comment]
代码渲染我是用的highlight.js里的一个叫做atom-one-dark的皮肤，我觉得这个皮肤挺好看的哈哈。。
如果想换的话，https://highlightjs.org/ 在这个网站里挑选自己喜欢的样式，放到source/css下，然后将原有的layout/_partial的head.ejs引入就行了。。嘿嘿。
