### ISSUE TITLE
希望可以增加文章头图和优化文章评论模块

### ISSUE THREAD

**Issue by Leonhzz** [lsylovelmy/hexo-theme-macleaya#2]
大爱macleaya的这种排版布局
但是，如果能够增加文章头图，像这样：
![image](https://user-images.githubusercontent.com/53173411/87844867-29f94980-c8f4-11ea-9cbc-8abc10cfb762.png)
感觉将会很棒。
有试过想于博主交流下，但是发现评论模块不太友好。（LOL）

**Comment by lsy-loren** [comment]
谢谢支持哈，这个要加也挺简单的，只需要改一下layout/index.ejs里面的布局就行了哈。
